apiVersion: batch/v1
kind: Job
metadata:
  name: cis_3_2_6
  namespace: kube-system
spec:
  template:
    spec:
      serviceAccountName: cluster-admin-sa
      restartPolicy: Never
      containers:
      - name: cis_3_2_6
        image: bitnami/kubectl:latest
        command:
          - /bin/sh
          - -c
          - |
            echo "=== CIS 3.2.6 - Ensure that the --make-iptables-util-chains argument is set to true "

            NODES=$(kubectl get nodes -o jsonpath='{.items[*].metadata.name}')

            for NODE in $NODES; do
              echo "---- Node: $NODE ----"

              RAW=$(kubectl get --raw /api/v1/nodes/$NODE/proxy/configz 2>/dev/null || echo "")

              if [ -z "$RAW" ]; then
                echo "[INFO] /configz not accessible for $NODE. Assuming EKS defaults."
                echo "[PASS] makeIPTablesUtilChains default is true"
                continue
              fi

              VALUE=$(echo "$RAW" | jq -r '.kubeletconfig.makeIPTablesUtilChains // empty')

            
              if [ -z "$VALUE" ]; then
                echo "[INFO] makeIPTablesUtilChains not defined -> using default"
                echo "[PASS] makeIPTablesUtilChains is true by default"
                continue
              fi

          
              if [ "$VALUE" = "true" ]; then
                echo "[PASS] makeIPTablesUtilChains=true"
              else
                echo "[FAIL] makeIPTablesUtilChains=$VALUE"
              fi

            done

            echo "Audit complete"

      nodeSelector:
        kubernetes.io/os: linux
