name: specializedProjects

on: 
  workflow_dispatch:
    inputs:
      ALLOWED_CIDR:
        description: Your Public IP
        required: false
        default: ''
        
  push:
    branches: ["main"]
  pull_request:
    branches:
      - main 
    

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  BUCKET_TF_STATE: ${{secrets.BUCKET_TF_STATE}}
  EKS_CLUSTER: ${{secrets.EKS_CLUSTER}}
  ECR_REPOSITORY: ${{secrets.ECR_REPOSITORY}}

jobs:
  Cis_Check:
    runs-on: ubuntu-latest
    needs: Node_Cis_Check
    name: "CIS Benchmark Check"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip curl
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --update
      
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}


      # CIS 2.1 Logging
      - name: 2.1 Logging
        run: |
             cd cischeck/2.1_Logging
             chmod +x cis_2_1_1.sh
             ./cis_2_1_1.sh ${{env.EKS_CLUSTER}} ${{env.AWS_REGION}}

      # CIS 5.1 Image Registry
      - name: 5.1 Image Registry
        run: |
            cd cischeck/5.1_Image_Registry
            chmod +x cis_5_1_1.sh
            ./cis_5_1_1.sh ${{env.AWS_REGION}} ${{env.ECR_REPOSITORY}}

      # CIS 4.1 RBAC Service Account
      - name: 4.1 RBAC Service Account
        run: |
          cd cischeck/4.1_RBAC_ServiceAccount
          chmod +x audit_cis_rbac.sh
          ./audit_cis_rbac.sh
      
      - name: 4.2 Audit Pod Security
        run: |
          cd cischeck/4.2_audit_pod_security
          chmod +x audit_cis_pod_security.sh
          ./audit_cis_pod_security.sh

      # CIS 5.4 Cluster Networking
      - name: 5.4.2 Private Endpoint Enabled, Public Disabled
        run: |
          cd cischeck/5.4_CLUSTER_NETWORKING
          chmod +x cis_5_4_2.sh
          ./cis_5_4_2.sh ${{ env.AWS_REGION }} ${{ env.EKS_CLUSTER }} ${{ github.event.inputs.ALLOWED_CIDR }}

      - name: 5.4.3 Ensure Private Nodes
        run: |
          cd cischeck/5.4_CLUSTER_NETWORKING
          chmod +x cis_5_4_3.sh
          ./cis_5_4_3.sh ${{ env.AWS_REGION }} ${{ env.EKS_CLUSTER }}

      - name: 5.4.4 Ensure Network Policy is Enabled and set as appropriate
        run: |
          kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.14.5/install/kubernetes/quick-install.yaml
          kubectl wait --for=condition=Ready pods -n kube-system -l k8s-app=cilium --timeout=420s
          cd cischeck/5.4_CLUSTER_NETWORKING
          chmod +x cis_5_4_4.sh
          ./cis_5_4_4.sh ${{ env.AWS_REGION }} ${{ env.EKS_CLUSTER }}


      - name: 5.4.1 Restrict Control Plane Endpoint
        run: |
          cd cischeck/5.4_CLUSTER_NETWORKING
          chmod +x cis_5_4_1.sh
          ./cis_5_4_1.sh ${{ env.EKS_CLUSTER }} ${{ env.AWS_REGION }} ${{ github.event.inputs.ALLOWED_CIDR }}


  Node_Cis_Check:
    runs-on: ubuntu-latest
    name: "CIS Worker Node Check"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Verify cluster connection
        run: kubectl get nodes

      - name: Apply privileged pod
        run: |
          kubectl apply -f cischeck/3.1_Worker_Node_Configuration/file-check-pod.yaml

      - name: Wait for pod ready
        run: kubectl wait --for=condition=Ready pod/file-check --timeout=120s

      # CIS 3.1 Worker_Node_Configuration
      - name: 3.1.1 Ensure that the kubeconfig file permissions are set to 644 or more restrictive
        run: |
          cd cischeck/3.1_Worker_Node_Configuration
          chmod +x cis_3_1_1.sh
          ./cis_3_1_1.sh
      
      - name: 3.1.2 Ensure that the kubelet kubeconfig file ownership is set to root:root
        run: |
          cd cischeck/3.1_Worker_Node_Configuration
          chmod +x cis_3_1_2.sh
          ./cis_3_1_2.sh

      - name: 3.1.3 Ensure that the kubelet configuration file has permissions set to 644 or more restrictive
        run: |
          cd cischeck/3.1_Worker_Node_Configuration
          chmod +x cis_3_1_3.sh
          ./cis_3_1_3.sh

      - name: 3.1.4 Ensure that the kubelet configuration file ownership is set to root:root ===
        run: |
          cd cischeck/3.1_Worker_Node_Configuration
          chmod +x cis_3_1_4.sh
          ./cis_3_1_4.sh
      # CIS 5.2 IAM
      - name: 5.2 IAM
        run: |
            cd cischeck/5.2_IAM
            chmod +x cis_5_2_1.sh
            ./cis_5_2_1.sh

      - name: Copy CIS scripts to pod
        run: |
          kubectl cp cischeck/3.2_Kubelet/ file-check:/tmp/cischeck/

      - name: Apply cluster-admin ServiceAccount
        run: kubectl apply -f cischeck/3.2_Kubelet/sa-cluster-admin.yaml -n kube-system

      - name: Run CIS 3.2.x Jobs
        run: |
          NAMESPACE=kube-system
          for i in {1..9}; do
            JOB_FILE="cischeck/3.2_Kubelet/cis-3-2-$i.yaml"
            echo "=== Applying $JOB_FILE ==="
            kubectl apply -f $JOB_FILE

            # Lấy tên Job từ file
            JOB_NAME="cis-3-2-$i"
            # Chờ Job hoàn thành
            kubectl wait --for=condition=complete --timeout=30s job/$JOB_NAME -n $NAMESPACE || echo "[WARN] Job $JOB_NAME timeout"

            # Lấy log Pod
            POD_NAME=$(kubectl get pods -n $NAMESPACE -l job-name=$JOB_NAME -o jsonpath='{.items[0].metadata.name}')
            echo "---- Logs for $JOB_NAME ----"
            kubectl logs $POD_NAME -n $NAMESPACE
            echo "---------------------------"
          done